{% set name = "pysmb" %}
{% set version = "1.2.10" %}
{% set sha256 = "5796253bf10d0c5fbeae3d5ae89c66c275d1b3e547f0bc55b7d4799168b19076" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyasn1

test:
  imports:
    - smb
    - nmb
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/miketeo/pysmb
  license: Zlib
  license_file: LICENSE
  summary: pysmb is an experimental SMB/CIFS library written in Python to support file sharing between Windows and Linux machine
  doc_url: https://github.com/miketeo/pysmb
  dev_url: https://github.com/miketeo/pysmb

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
