{% set name = "pysmb" %}
{% set version = "1.2.13" %}
{% set sha256 = "89d37fc4f061acecf40e6864e555898f2ecc49994ec06949edbb94b94239a808" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyasn1

test:
  imports:
    - smb
    - nmb
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/miketeo/pysmb
  license: Zlib
  license_file: LICENSE
  summary: pysmb is an experimental SMB/CIFS library written in Python to support file sharing between Windows and Linux machine
  doc_url: https://github.com/miketeo/pysmb
  dev_url: https://github.com/miketeo/pysmb

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
